# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:  
  deploy-backend:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo/nettour-backend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - backend-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: backend-dependencies-{{ checksum "package.json" }}
      - run: yarn deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:     
      - deploy-backend:
          filters:
            branches:
              only: circle