service:
  name: api-nettour

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
#  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1	
  stage: prod
  environment:
    SECRET_KEY: ${env:SECRET_KEY}    
    JWT_KEY: ${env:JWT_SECRET}
    MONGO_URI : ${env:MONGO_URI} 
    S3_KEY : ${env:AWS_S3_ACCESS_KEY_ID}
    S3_SECRET_KEY : ${env:AWS_S3_SECRET_KEY_ID}
    EMAIL : ${env:AUTH_EMAIL}
    EMAIL_PASSWORD : ${env:AUTH_PASSWORD}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DetachNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
      Resource: '*'

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://nettour.cf'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://nettour.cf'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
    vpc:
      securityGroupIds:
        - sg-5bc57830
        - sg-056b9986a73e2f766
      subnetIds:
        - subnet-91481ef9
        - subnet-4f59dc03 

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'